spring:
  application:
    name: usian-order-web
server:
  port: 8103
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
# 请求连接的超时时间
ribbon:
  ConnectTimeout: 6000
  # 请求处理的超时时间
  ReadTimeout: 6000
